site_name: Techlan London 2023
site_description: 'Hello TechLan London'
site_author: 'Gregory Bennett'
docs_dir: docs/
repo_name: 'techlan23/techlan-london'
repo_url: 'https://github.com/techlan23/techlan-london'
nav:
    - Home: index.md
theme:
  name: material
  palette:
    scheme: slate
    primary: light blue
    accent: deep purple
